title: Rethinking Work & Life with Rhyd Lewis
url: https://rethinkingworklife.net
description: "The podcast that uncovers the defining moments that make people rethink their work & life."
keywords: "podcast,interview,business,social"
author:
  name: Orsobi Ltd.
header_pages:
  - about.md
  - contact.md
social_links:
  instagram: rethinkingworkandlife
future: true
date_format: "%B %d, %Y"
acast-show-name: rethink-everything
acast-show-id: 63440d1a71ca7a0012e0f3d1
itunes-show-id: rethink-everything/id1652090407
overcast-show-id: p4012515-3NrjbG
spotify-show-id: 4UACxKSbtgRbSg5KfFy621
plausible-domain: rethinkingworklife.net
plausible-src: https://plausible.io/js/plausible.js
