title: Rethink Everything
email: hello@rethinkeverything.show
url: https://rehinkeverything.show
description: "The podcast that uncovers the critical moments in life that make people pause, reflect and rethink everything."
keywords: "podcast,interview,business,social"
author:
  name: Orsobi Ltd.
header_pages:
  - about.md
  - contact.md
social_links:
  twitter: RTEverythingPod
future: true
date_format: "%B %d, %Y"
acast-show-id: rethink-everything
itunes-show-id:
overcast-show-id:
spotify-show-id:
podfollow-show-id:
plausible-domain: rethinkeverything.show
plausible-src: https://plausible.io/js/plausible.js
#plausible-src: https://plausible.io/js/script.local.js
